### ISSUE TITLE
Cluster Checklist

### ISSUE THREAD

**Issue by maximiliancsuk** [max-bytes/omnikeeper#162]
- [x] Quartz: check if everything runs properly and jobs are scheduled correctly
- [x] CLB Last-Run-Cache: make work in clustered environment
- [x] GraphQLSchemaReloader: check if it works properly and data is properly held and updated
- [x] EdmModelReloader: check if it works properly and data is properly held and updated
- [x] Online Inbound Adapter mapping table (OIA quo vadis)... tracked further in #206
